### ISSUE TITLE
Fails to run on Mac

### ISSUE THREAD

**Issue by pgarba** [DenuvoSoftwareSolutions/GAMBA#1]
Hi,

Seems not work on my Mac. Any idea what's wrong ?

Thanks,
Peter

```
❯ python3 src/simplify_general.py "-x" -b 32 -m
*** Expression -x
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GeneralSimplifier' object has no attribute '__simplify'. Did you mean: 'simplify'?
No simplification result!
```

**Comment by fvrmatteo** [comment]
The issue seems to be related to the mangling of the private method name [1](https://stackoverflow.com/questions/57497370/python-multiprocessing-mapping-private-method), [2](https://stackoverflow.com/questions/1301346/what-is-the-meaning-of-single-and-double-underscore-before-an-object-name).

For me it was sufficient to change `__simplify` (double underscore prefix) to `_simplify` (single underscore prefix) in the `GeneralSimplifier` class and adjust it on the `multiprocessing.Process` call too.

I think this might be one solution, but if there's a better one I'm curious to learn about it.

**Comment by pgarba** [comment]
Works!

Thanks for the hint

**Comment by pmeerw** [comment]
probably related to https://bugs.python.org/issue44675; don't have a Mac

pushed a fix following @fvrmatteo's suggestion, thx guys!

**Comment by pmeerw** [comment]
workaround in place, closing this issue
