### ISSUE TITLE
Simplify.py not terminating on linear input 

### ISSUE THREAD

**Issue by Colton1skees** [DenuvoSoftwareSolutions/GAMBA#3]
Given the linear expression `(v3+((((((im|v2)^v0)^v4)|v5)^v6)&(~v3)))*1658171697`, simplify.py does not terminate within 30 minutes. Note that the original SiMBA implementation does terminate on this input.

**Comment by breichenwallner** [comment]
Thanks for reporting!

This was due to a high computational effort at the creation of a bitwise expression with 7 variables. The performance here is now improved very significantly, should now finish within a few seconds.

This creation is not included in the original SiMBA algorithm, where a quite complex linear combination is returned. The result given by GAMBA is just slightly simpler, since we did not go for a full optimization at this part of the algorithm.

**Comment by Colton1skees** [comment]
Thanks for fixing this. 

Here's a similar edge case to the one from above, `0x10FE63879ACC9A2A * ((a5 & a4 & a3 & ~a6 & v6) + (v21 & a5 & a4 & a3 & a1 & ~a6) + (a5 & a4 & a2 & a1 & ~a6 & ~a3)) + 0xEB7FAE3079DAD87 * ((a6 & a2 & a1 & ~a5 & v7 & v8) + (a6 & a3 & a2 & ~a5 & v25) + (a5 | a1 ^ v8 & (a2 ^ (a5 | a4)))) - 0xE878DD33CDC5232 * ((a5 & a3 & ~a6 & v7 & v6) + (a5 & a3 & a1 & ~a6 & v9) + (~a1 & a5 & a4 & a3 & a2 & ~a6) + (a5 & a4 & a3 & a2 & a1 & ~a6) + (a5 & a3 & v7 & a2 & a1 & ~a6))` which still causes `simplify_general.py` to run for about ~10 minutes. The output returned for this example is 104x larger than the output from the original SiMBA algorithm.

**Comment by Colton1skees** [comment]
In practice the variable count of that last example is probably too high for the difference in runtime to matter.
